name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-wheels:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*

  build-sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist

      - uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/*

  publish:
    needs:
      - build-wheels
      - build-sdist

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir upload
          find dist -type f \( -name "*.whl" -o -name "*.tar.gz" \) -exec cp {} upload/ \;

      - name: Verify artifacts
        run: ls -lah upload

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: upload
        if: startsWith(github.ref, 'refs/tags/v')
